description: No signal processing.
devices:
  adjust_period: null
  capture:
    channels: 2
    extra_samples: null
    filename: /dev/stdin
    format: FLOAT64LE
    read_bytes: null
    skip_bytes: null
    type: File
  capture_samplerate: null
  chunksize: 4096
  enable_rate_adjust: null
  playback:
    channels: 2
    device: plughw:0,0
    format: FLOAT64LE
    type: Alsa
  queuelimit: 1
  rate_measure_interval: null
  resampler: null
  samplerate: 768000
  silence_threshold: null
  silence_timeout: null
  stop_on_rate_change: null
  target_level: null
  volume_ramp_time: 150
filters:
  Filter_00:
    description: 'Filter: ON LSC Fc 110 Hz Gain -1.5 dB Q 0.9'
    parameters:
      freq: 110.0
      gain: -1.5
      q: 0.9
      type: Lowshelf
    type: Biquad
  Filter_01:
    description: 'Filter: ON PK Fc 200 Hz Gain -2 dB Q 1'
    parameters:
      freq: 200.0
      gain: -2.0
      q: 1.0
      type: Peaking
    type: Biquad
  Filter_02:
    description: 'Filter: ON LSC Fc 400 Hz Gain -1 dB Q 0.9'
    parameters:
      freq: 400.0
      gain: -1.0
      q: 0.9
      type: Lowshelf
    type: Biquad
  Filter_03:
    description: 'Filter: ON LSC Fc 1000 Hz Gain -1 dB Q 0.6'
    parameters:
      freq: 1000.0
      gain: -1.0
      q: 0.6
      type: Lowshelf
    type: Biquad
  Filter_04:
    description: 'Filter: ON PK Fc 1900 Hz Gain -1 dB Q 1.5'
    parameters:
      freq: 1900.0
      gain: -1.0
      q: 1.5
      type: Peaking
    type: Biquad
  Filter_05:
    description: 'Filter: ON PK Fc 3000 Hz Gain -3 dB Q 1.4'
    parameters:
      freq: 3000.0
      gain: -3.0
      q: 1.4
      type: Peaking
    type: Biquad
  Filter_06:
    description: 'Filter: ON HSC Fc 4000 Hz Gain -1 dB Q 2'
    parameters:
      freq: 4000.0
      gain: -1.0
      q: 2.0
      type: Highshelf
    type: Biquad
  Filter_07:
    description: 'Filter: ON HSC Fc 4000 Hz Gain 1 dB Q 0.9'
    parameters:
      freq: 4000.0
      gain: 1.0
      q: 0.9
      type: Highshelf
    type: Biquad
  Filter_08:
    description: 'Filter: ON HSC Fc 5000 Hz Gain 1 dB Q 2'
    parameters:
      freq: 5000.0
      gain: 1.0
      q: 2.0
      type: Highshelf
    type: Biquad
  Filter_09:
    description: 'Filter: ON HSC Fc 5700 Hz Gain -2 dB Q 3'
    parameters:
      freq: 5700.0
      gain: -2.0
      q: 3.0
      type: Highshelf
    type: Biquad
  Filter_10:
    description: 'Filter: ON HSC Fc 6000 Hz Gain -1 dB Q 0.9'
    parameters:
      freq: 6000.0
      gain: -1.0
      q: 0.9
      type: Highshelf
    type: Biquad
  Filter_11:
    description: 'Filter: ON HSC Fc 6500 Hz Gain 2 dB Q 3'
    parameters:
      freq: 6500.0
      gain: 2.0
      q: 3.0
      type: Highshelf
    type: Biquad
  Filter_12:
    description: 'Filter: ON HSC Fc 8000 Hz Gain 2 dB Q 0.7'
    parameters:
      freq: 8000.0
      gain: 2.0
      q: 0.7
      type: Highshelf
    type: Biquad
  Filter_13:
    description: 'Filter: ON PK Fc 8000 Hz Gain -4 dB Q 3'
    parameters:
      freq: 8000.0
      gain: -4.0
      q: 3.0
      type: Peaking
    type: Biquad
  Filter_14:
    description: 'Filter: ON PK Fc 10000 Hz Gain -10 dB Q 1.9'
    parameters:
      freq: 10000.0
      gain: -10.0
      q: 1.9
      type: Peaking
    type: Biquad
  Filter_15:
    description: 'Filter: ON PK Fc 12000 Hz Gain -4 dB Q 1.8'
    parameters:
      freq: 12000.0
      gain: -4.0
      q: 1.8
      type: Peaking
    type: Biquad
  Filter_16:
    description: 'Filter: ON PK Fc 15000 Hz Gain -9 dB Q 1.3087'
    parameters:
      freq: 15000.0
      gain: -9.0
      q: 1.3087
      type: Peaking
    type: Biquad
  Preamp_17:
    description: 'Preamp: -1.5 dB'
    parameters:
      gain: -1.5
      scale: dB
    type: Gain
mixers:
  stereo:
    channels:
      in: 2
      out: 2
    description: null
    mapping:
    - dest: 0
      mute: null
      sources:
      - channel: 0
        gain: 0
        inverted: null
        mute: null
        scale: null
    - dest: 1
      mute: null
      sources:
      - channel: 1
        gain: 0
        inverted: null
        mute: null
        scale: null
pipeline:
- bypassed: null
  description: null
  name: stereo
  type: Mixer
- channel: 0
  description: Default, all channels
  names:
  - Filter_00
  - Filter_01
  - Filter_02
  - Filter_03
  - Filter_04
  - Filter_05
  - Filter_06
  - Filter_07
  - Filter_08
  - Filter_09
  - Filter_10
  - Filter_11
  - Filter_12
  - Filter_13
  - Filter_14
  - Filter_15
  - Filter_16
  - Preamp_17
  type: Filter
- channel: 1
  description: Default, all channels
  names:
  - Filter_00
  - Filter_01
  - Filter_02
  - Filter_03
  - Filter_04
  - Filter_05
  - Filter_06
  - Filter_07
  - Filter_08
  - Filter_09
  - Filter_10
  - Filter_11
  - Filter_12
  - Filter_13
  - Filter_14
  - Filter_15
  - Filter_16
  - Preamp_17
  type: Filter
processors: null
title: null
