description: No signal processing.
devices:
  adjust_period: null
  capture:
    channels: 2
    extra_samples: null
    filename: /dev/stdin
    format: FLOAT64LE
    read_bytes: null
    skip_bytes: null
    type: File
  capture_samplerate: null
  chunksize: 4096
  enable_rate_adjust: null
  playback:
    channels: 2
    device: plughw:0,0
    format: FLOAT64LE
    type: Alsa
  queuelimit: 1
  rate_measure_interval: null
  resampler: null
  samplerate: 768000
  silence_threshold: null
  silence_timeout: null
  stop_on_rate_change: null
  target_level: null
  volume_ramp_time: 150
filters:
  Filter_0:
    description: 'Filter: ON PK Fc 100 Hz Gain -2 dB Q 1.4'
    parameters:
      freq: 100.0
      gain: -2.0
      q: 1.4
      type: Peaking
    type: Biquad
  Filter_1:
    description: 'Filter: ON LSC Fc 200 Hz Gain 2 dB Q 0.9'
    parameters:
      freq: 200.0
      gain: 2.0
      q: 0.9
      type: Lowshelf
    type: Biquad
  Filter_2:
    description: 'Filter: ON LSC Fc 500 Hz Gain -2 dB Q 0.9'
    parameters:
      freq: 500.0
      gain: -2.0
      q: 0.9
      type: Lowshelf
    type: Biquad
  Filter_3:
    description: 'Filter: ON PK Fc 3000 Hz Gain -1 dB Q 1.4'
    parameters:
      freq: 3000.0
      gain: -1.0
      q: 1.4
      type: Peaking
    type: Biquad
  Filter_4:
    description: 'Filter: ON HSC Fc 4000 Hz Gain -2 dB Q 2'
    parameters:
      freq: 4000.0
      gain: -2.0
      q: 2.0
      type: Highshelf
    type: Biquad
  Filter_5:
    description: 'Filter: ON HSC Fc 5000 Hz Gain 2 dB Q 2'
    parameters:
      freq: 5000.0
      gain: 2.0
      q: 2.0
      type: Highshelf
    type: Biquad
  Filter_6:
    description: 'Filter: ON LSC Fc 7000 Hz Gain -3 dB Q 0.3'
    parameters:
      freq: 7000.0
      gain: -3.0
      q: 0.3
      type: Lowshelf
    type: Biquad
  Preamp_7:
    description: 'Preamp: -2 dB'
    parameters:
      gain: -2.0
      scale: dB
    type: Gain
mixers:
  stereo:
    channels:
      in: 2
      out: 2
    description: null
    mapping:
    - dest: 0
      mute: null
      sources:
      - channel: 0
        gain: 0
        inverted: null
        mute: null
        scale: null
    - dest: 1
      mute: null
      sources:
      - channel: 1
        gain: 0
        inverted: null
        mute: null
        scale: null
pipeline:
- bypassed: null
  description: null
  name: stereo
  type: Mixer
- channel: 0
  description: Default, all channels
  names:
  - Filter_0
  - Filter_1
  - Filter_2
  - Filter_3
  - Filter_4
  - Filter_5
  - Filter_6
  - Preamp_7
  type: Filter
- channel: 1
  description: Default, all channels
  names:
  - Filter_0
  - Filter_1
  - Filter_2
  - Filter_3
  - Filter_4
  - Filter_5
  - Filter_6
  - Preamp_7
  type: Filter
processors: null
title: null
