description: No signal processing.
devices:
  adjust_period: null
  capture:
    channels: 2
    extra_samples: null
    filename: /dev/stdin
    format: FLOAT64LE
    read_bytes: null
    skip_bytes: null
    type: File
  capture_samplerate: null
  chunksize: 4096
  enable_rate_adjust: null
  playback:
    channels: 2
    device: plughw:0,0
    format: FLOAT64LE
    type: Alsa
  queuelimit: 1
  rate_measure_interval: null
  resampler: null
  samplerate: 768000
  silence_threshold: null
  silence_timeout: null
  stop_on_rate_change: null
  target_level: null
  volume_ramp_time: 150
filters:
  Filter_0:
    description: 'Filter: ON LS Fc 50 Hz Gain 2 dB'
    parameters:
      freq: 50.0
      gain: 2.0
      q: 0.9
      type: Lowshelf
    type: Biquad
  Filter_1:
    description: 'Filter: ON PK Fc 1500 Hz Gain 1 dB Q 1'
    parameters:
      freq: 1500.0
      gain: 1.0
      q: 1.0
      type: Peaking
    type: Biquad
  Filter_2:
    description: 'Filter: ON HS Fc 4000 Hz Gain 2 dB'
    parameters:
      freq: 4000.0
      gain: 2.0
      q: 0.9
      type: Peaking
    type: Biquad
  Filter_3:
    description: 'Filter: ON PK Fc 8500 Hz Gain -9 dB Q 5'
    parameters:
      freq: 8500.0
      gain: -9.0
      q: 5.0
      type: Peaking
    type: Biquad
  Filter_4:
    description: 'Filter: ON PK Fc 10000 Hz Gain -6 dB Q 3'
    parameters:
      freq: 10000.0
      gain: -6.0
      q: 3.0
      type: Peaking
    type: Biquad
  Filter_5:
    description: 'Filter: ON PK Fc 11500 Hz Gain -5 dB Q 3'
    parameters:
      freq: 11500.0
      gain: -5.0
      q: 3.0
      type: Peaking
    type: Biquad
  Filter_6:
    description: 'Filter: ON PK Fc 13000 Hz Gain -5 dB Q 2'
    parameters:
      freq: 13000.0
      gain: -5.0
      q: 2.0
      type: Peaking
    type: Biquad
  Preamp_7:
    description: 'Preamp: -1 dB'
    parameters:
      gain: '-1'
      scale: dB
    type: Gain
mixers:
  stereo:
    channels:
      in: 2
      out: 2
    description: null
    mapping:
    - dest: 0
      mute: null
      sources:
      - channel: 0
        gain: 0
        inverted: null
        mute: null
        scale: null
    - dest: 1
      mute: null
      sources:
      - channel: 1
        gain: 0
        inverted: null
        mute: null
        scale: null
pipeline:
- bypassed: null
  description: null
  name: stereo
  type: Mixer
- channel: 0
  description: Default, all channels
  names:
  - Filter_0
  - Filter_1
  - Filter_2
  - Filter_3
  - Filter_4
  - Filter_5
  - Filter_6
  - Preamp_7
  type: Filter
- channel: 1
  description: Default, all channels
  names:
  - Filter_0
  - Filter_1
  - Filter_2
  - Filter_3
  - Filter_4
  - Filter_5
  - Filter_6
  - Preamp_7
  type: Filter
processors: null
title: null
