description: No signal processing.
devices:
  adjust_period: null
  capture:
    channels: 2
    extra_samples: null
    filename: /dev/stdin
    format: FLOAT64LE
    read_bytes: null
    skip_bytes: null
    type: File
  capture_samplerate: null
  chunksize: 4096
  enable_rate_adjust: null
  playback:
    channels: 2
    device: plughw:0,0
    format: FLOAT64LE
    type: Alsa
  queuelimit: 1
  rate_measure_interval: null
  resampler: null
  samplerate: 768000
  silence_threshold: null
  silence_timeout: null
  stop_on_rate_change: null
  target_level: null
  volume_ramp_time: 150
filters:
  Filter_00:
    description: 'Filter: ON PK Fc 90 Hz Gain -4.9 dB Q 0.3'
    parameters:
      freq: 90.0
      gain: -4.9
      q: 0.3
      type: Peaking
    type: Biquad
  Filter_01:
    description: 'Filter: ON LSC Fc 105 Hz Gain 3 dB Q 0.71'
    parameters:
      freq: 105.0
      gain: 3.0
      q: 0.71
      type: Lowshelf
    type: Biquad
  Filter_02:
    description: 'Filter: ON PK Fc 1330 Hz Gain -4 dB Q 1'
    parameters:
      freq: 1330.0
      gain: -4.0
      q: 1.0
      type: Peaking
    type: Biquad
  Filter_03:
    description: 'Filter: ON PK Fc 2200 Hz Gain 1.4 dB Q 2.5'
    parameters:
      freq: 2200.0
      gain: 1.4
      q: 2.5
      type: Peaking
    type: Biquad
  Filter_04:
    description: 'Filter: ON PK Fc 3000 Hz Gain -2.6 dB Q 3'
    parameters:
      freq: 3000.0
      gain: -2.6
      q: 3.0
      type: Peaking
    type: Biquad
  Filter_05:
    description: 'Filter: ON PK Fc 3700 Hz Gain -2.1 dB Q 5'
    parameters:
      freq: 3700.0
      gain: -2.1
      q: 5.0
      type: Peaking
    type: Biquad
  Filter_06:
    description: 'Filter: ON PK Fc 4300 Hz Gain 2 dB Q 4'
    parameters:
      freq: 4300.0
      gain: 2.0
      q: 4.0
      type: Peaking
    type: Biquad
  Filter_07:
    description: 'Filter: ON PK Fc 5950 Hz Gain -4.1 dB Q 10'
    parameters:
      freq: 5950.0
      gain: -4.1
      q: 10.0
      type: Peaking
    type: Biquad
  Filter_08:
    description: 'Filter: ON PK Fc 6600 Hz Gain 2 dB Q 7'
    parameters:
      freq: 6600.0
      gain: 2.0
      q: 7.0
      type: Peaking
    type: Biquad
  Filter_09:
    description: 'Filter: ON PK Fc 7500 Hz Gain 1 dB Q 3'
    parameters:
      freq: 7500.0
      gain: 1.0
      q: 3.0
      type: Peaking
    type: Biquad
  Filter_10:
    description: 'Filter: ON PK Fc 12000 Hz Gain -8 dB Q 8'
    parameters:
      freq: 12000.0
      gain: -8.0
      q: 8.0
      type: Peaking
    type: Biquad
mixers:
  stereo:
    channels:
      in: 2
      out: 2
    description: null
    mapping:
    - dest: 0
      mute: null
      sources:
      - channel: 0
        gain: 0
        inverted: null
        mute: null
        scale: null
    - dest: 1
      mute: null
      sources:
      - channel: 1
        gain: 0
        inverted: null
        mute: null
        scale: null
pipeline:
- bypassed: null
  description: null
  name: stereo
  type: Mixer
- channel: 0
  description: Default, all channels
  names:
  - Filter_00
  - Filter_01
  - Filter_02
  - Filter_03
  - Filter_04
  - Filter_05
  - Filter_06
  - Filter_07
  - Filter_08
  - Filter_09
  - Filter_10
  type: Filter
- channel: 1
  description: Default, all channels
  names:
  - Filter_00
  - Filter_01
  - Filter_02
  - Filter_03
  - Filter_04
  - Filter_05
  - Filter_06
  - Filter_07
  - Filter_08
  - Filter_09
  - Filter_10
  type: Filter
processors: null
title: null
